name: 芝嫲视频

on:
  workflow_dispatch:
  schedule:
     - cron: '0 * * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        ZM_zhimabody: ${{ secrets.ZM_zhimabody }}
        ZM_zhimatxbody: ${{ secrets.ZM_zhimatxbody }}		
        
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/yifan-BEN10/ZHIYONG.git ~/ZHIYONG
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        if: env.ZM_zhimabody
        run: |
          cd ~/ZHIYONG
          git checkout ZIYE
          npm install
      - name: '运行 【芝嫲视频】'
        if: env.ZM_zhimabody
        run: |
          cd ~/ZHIYONG
          node Task/zhima.js
        env:
          
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
