name: 笑谱

on:
  workflow_dispatch:
  schedule:
     - cron: '0,30 0-23 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        XP_refreshTOKEN: ${{ secrets.XP_refreshTOKEN }}
        XP_CASH: ${{ secrets.XP_CASH }}		
        XP_live: ${{ secrets.XP_live }}	
        
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/yifan-BEN10/ZHIYONG.git ~/ZHIYONG
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        if: env.XP_refreshTOKEN
        run: |
          cd ~/ZHIYONG
          git checkout ZIYE
          npm install
      - name: '运行 【笑谱】'
        if: env.XP_refreshTOKEN
        run: |
          cd ~/ZHIYONG
          node Task/iboxpay.js
        env:
          
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
